laser:
  mass: 0.1          # Motor mass in Kg
  radius: 0.015     # Wheel radius in m
  length: 0.01      # Wheel length in m, considering is as a cylinder
  mesh: '' #'rplidar-a2.stl'  # Name of the mesh files. Leave it empty ('') to have a red wheel
  #mesh: ''
  dx: 0.0
  dy: 0.0
  dz: 0.04
  angular_range:
    min: -3.1415
    max: 3.1415
  color: Gazebo/Grey
  enable_gpu: false

camera:
  mass: 0.1             # Mass in Kg
  radius: 0.03          # Radius of the visual and collision geometry
  length: 0.1           # Length of the visual and collision geometry
  mesh: 'hokuyo.dae' 
  dx: 0.40
  dy: 0.0
  dz: 0.04
  scale: 1 1 1
  meshes:
    scale: 1 1 1      # Scale for the mesh